# Generated by Django 4.1.3 on 2022-11-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracticeEnglish', '0002_remove_new_thing_ithink_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_thing_very',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.CharField(max_length=30)),
                ('example', models.CharField(max_length=60)),
            ],
        ),
    ]
